spring.application.name=demo

# This tells Java to look for the Render Environment Variables, and use localhost as a backup!
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/Todo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=1234

logging.level.org.springframework.security=TRACE